name: weather_service
description: A test flutter project for GPN.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Firebase servicies
  firebase_core: ^2.14.0
  firebase_auth: ^4.6.3
  # Code generator for assets, fonts, colors
  flutter_gen: ^5.3.1
  # Freezed annotation
  freezed_annotation: ^2.2.0
  # Handling JSON
  json_annotation: ^4.8.1
  # Router
  go_router: ^9.0.0
  # Service locator
  get_it: ^7.6.0
  # Geolocation
  geolocator: ^9.0.2
  geocoding: ^2.1.0
  # Bloc
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  bloc_test: ^9.1.3
  # Validate form
  formz: ^0.6.0
  # HTTP client and retrofit
  dio: ^4.0.6
  retrofit: ^3.3.1
  # Google fonts
  google_fonts: ^5.1.0
  # SVG
  flutter_svg: ^2.0.7
  # Streams
  rxdart: ^0.27.7
  # Symblos
  angles: ^2.1.1
  # Network connect
  connectivity_plus: ^4.0.1
  # Hive
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  # SQLite
  sqflite: ^2.2.8+4
  path: ^1.8.3

  #Animated native splash screen
  #aka Stefan
  animated_splash_screen:
    git:
      url: https://github.com/StefanZlobin/animated_splash_screen.git
      ref: master

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.2

  flutter_lints: ^2.0.0
  build_runner: ^2.4.5
  freezed: ^2.3.5
  json_serializable: ^6.7.0
  go_router_builder: ^2.2.0
  flutter_gen_runner: ^5.3.1
  retrofit_generator: ^4.2.0
  hive_generator: ^2.0.0

flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 120 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/
